### ISSUE TITLE
Can you provide the mask images which can be used for removing background?

### ISSUE THREAD

**Issue by luowy1001** [weihaox/Multi-Modal-CelebA-HQ#1]

**Comment by weihaox** [comment]
Fixed at #https://github.com/IIGROUP/Multi-Modal-CelebA-HQ-Dataset/commit/7d2f8f55dd5e908b2f7e89370b8d87c0f0550e3e. Due to storage space limitations, I cannot upload this part of the images to Google Drive. The images with transparent backgound can be found at [Baidu Cloud](https://pan.baidu.com/s/17f9UVDiV9ELGNRvHbPbK7A) with password `tfpc`. You can save the alpha channel to obtain the mask.

**Comment by chaunceywx** [comment]
> Fixed at #[7d2f8f5](https://github.com/IIGROUP/MM-CelebA-HQ-Dataset/commit/7d2f8f55dd5e908b2f7e89370b8d87c0f0550e3e). Due to storage space limitations, I cannot upload this part of the images to Google Drive. The images with transparent backgound can be found at [Baidu Cloud](https://pan.baidu.com/s/17f9UVDiV9ELGNRvHbPbK7A) with password `tfpc`. You can save the alpha channel to obtain the mask.

The link seems to be dead, could you share it again?
