### ISSUE TITLE
How can I get your Dataset?

### ISSUE THREAD

**Issue by l1saK** [weihaox/Multi-Modal-CelebA-HQ#11]
Hi.  Thank you for your work!
I want to use  images with transparent background in my research.
Could you tell me how can i get your Dataset.
(Sorry, I'm a beginner at GitHub)

**Comment by weihaox** [comment]
Thanks for your interest of our work. The images with transparent background are unable to be uploaded due to the limited space. Generating the desired images can be achieved with ease by using various tools such as [Rembg](https://github.com/danielgatis/rembg) (an open-source tool), [removebg](https://www.remove.bg/) (a commercial software), and other tools that are available.

> For background removing, we use an open-source tool [Rembg](https://github.com/danielgatis/rembg) and a commercial software [removebg](https://www.remove.bg/). Different backgrounds can be further added using image composition or harmonization methods like [DoveNet](https://github.com/bcmi/Image_Harmonization_Datasets).
