### ISSUE TITLE
How to calculate the FID score for this dataset?

### ISSUE THREAD

**Issue by Corleone-Huang** [weihaox/Multi-Modal-CelebA-HQ#9]

**Comment by weihaox** [comment]
The proposed dataset is split as 24k for training and 6k for testing. We use the testing split of our dataset for FID calculation. We randomly sampled one from ten captions to generate one image, meaning to produce 6k generated images. These generated images are used to calculate FID (and LPIPS) with the 6k real ones in the testing set. Since previous text-to-image generation methods can only produce images with 256*256 resolution, we use a 14-layer StyleGAN implementation for fair comparisons.  I tend to use more images, eg 10 images for each caption, after recent discussions with other researchers. You can set a fair weight and keep it constant when generating batches of images  for the validation.
